# markdown: kramdown
# highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
  toc_levels: "2,3,4"
# gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50247134-3xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

repository: https://github.com/TCVan/tcvan.github.io
help_url: https://github.com/TCVan/tcvan.github.io

name: THPT Trần Cao Vân
description: THPT Trần Cao Vân
url: tcvan.edu.vn

fb_appid: 1792974517689740xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

logo: /img/logo-2x.png

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-auto-image
  # - jekyll-minifier
  
exclude:
  - vendor
  - .gitignore
  - README.md
  - .devcontainer
  - .vscode
  # - _dev
  # - _office
  # - _projects
  # - TCV
  # - _includes
  # - _layouts
  # - _data
  # - _sass

